// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT84ro_SdxQ-P_5NqV1qc7Id5galXiKTU',
    appId: '1:402677057975:web:3595d6cc407d2d36e98032',
    messagingSenderId: '402677057975',
    projectId: 'motel-reservation-feb47',
    authDomain: 'motel-reservation-feb47.firebaseapp.com',
    storageBucket: 'motel-reservation-feb47.firebasestorage.app',
    measurementId: 'G-32S84KHBD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjr9eF03eoPAQ7pUzpU603cgkcqtObyPg',
    appId: '1:402677057975:android:3c9307fc86ba9bb0e98032',
    messagingSenderId: '402677057975',
    projectId: 'motel-reservation-feb47',
    storageBucket: 'motel-reservation-feb47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_O3RF9opzNkox7nQOEM6wgoqkEuIHP8',
    appId: '1:402677057975:ios:183e3c94e1c8b419e98032',
    messagingSenderId: '402677057975',
    projectId: 'motel-reservation-feb47',
    storageBucket: 'motel-reservation-feb47.firebasestorage.app',
    iosBundleId: 'com.example.motelReservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_O3RF9opzNkox7nQOEM6wgoqkEuIHP8',
    appId: '1:402677057975:ios:183e3c94e1c8b419e98032',
    messagingSenderId: '402677057975',
    projectId: 'motel-reservation-feb47',
    storageBucket: 'motel-reservation-feb47.firebasestorage.app',
    iosBundleId: 'com.example.motelReservation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT84ro_SdxQ-P_5NqV1qc7Id5galXiKTU',
    appId: '1:402677057975:web:e6e1785e5428b21ee98032',
    messagingSenderId: '402677057975',
    projectId: 'motel-reservation-feb47',
    authDomain: 'motel-reservation-feb47.firebaseapp.com',
    storageBucket: 'motel-reservation-feb47.firebasestorage.app',
    measurementId: 'G-NW1JY565H5',
  );
}
